CREATE TABLE G_COMMENT (
    COMMENT_ID NUMBER PRIMARY KEY,
    GALLERY_ID NUMBER REFERENCES GALLERY(GALLERY_ID) ON DELETE CASCADE,
    USER_ID VARCHAR2(30) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONTENT VARCHAR2(300),
    REG_DATE DATE DEFAULT SYSDATE 
);

CREATE SEQUENCE G_COMM_SEQ;