CREATE TABLE GALLERY (
    GALLERY_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PHOTO VARCHAR2(100),
    TITLE VARCHAR2(100),
    AREA VARCHAR2(100),
    REG_DATE DATE DEFAULT SYSDATE 
);